// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmfuydnxclpzbepofpqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZnV5ZG54Y2xwemJlcG9mcHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODEwNDQsImV4cCI6MjA2MzY1NzA0NH0.hEQnB3vOPGTP4ODHs9oKYC1g-_xRZkEQ8wynm9OoEY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);